package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.GProduct;
import greendao.Customer;

import greendao.GProductDao;
import greendao.CustomerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gProductDaoConfig;
    private final DaoConfig customerDaoConfig;

    private final GProductDao gProductDao;
    private final CustomerDao customerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gProductDaoConfig = daoConfigMap.get(GProductDao.class).clone();
        gProductDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        gProductDao = new GProductDao(gProductDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);

        registerDao(GProduct.class, gProductDao);
        registerDao(Customer.class, customerDao);
    }
    
    public void clear() {
        gProductDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
    }

    public GProductDao getGProductDao() {
        return gProductDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

}
